apiVersion: v1
kind: Service
metadata:
  name: docs
  labels:
    app.kubernetes.io/name: docs
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: docs
