apiVersion: v1
kind: Service
metadata:
  name: docs
  labels:
    app.kubernetes.io/name: docs
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: docs
