apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: staging-redirect-to-https@kubernetescrd,staging-security-headers@kubernetescrd,staging-rate-limit@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - staging.lmbek.dk
        - placeholder1.staging.lmbek.dk
        - placeholder2.staging.lmbek.dk
        - docs.staging.lmbek.dk
        - web.staging.lmbek.dk
      secretName: staging-platform-tls
  rules:
    - host: staging.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-frontend
                port:
                  name: http
    - host: placeholder1.staging.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: placeholder1-service
                port:
                  name: http
    - host: placeholder2.staging.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: placeholder2-service
                port:
                  name: http
    - host: docs.staging.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  name: http
    - host: web.staging.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-frontend
                port:
                  name: http
