apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - namespace.yml
  - ../../base

patches:
  - path: ingress-patch.yml

images:
  - name: ghcr.io/lmbek/lmbek-hobby-web-frontend
    newTag: staging-latest
  - name: ghcr.io/lmbek/lmbek-hobby-placeholder1-service
    newTag: staging-latest
  - name: ghcr.io/lmbek/lmbek-hobby-placeholder2-service
    newTag: staging-latest
  - name: ghcr.io/lmbek/lmbek-hobby-docs
    newTag: staging-latest
