apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: production-redirect-to-https@kubernetescrd,production-security-headers@kubernetescrd,production-rate-limit@kubernetescrd
spec:
  tls:
    - hosts:
        - lmbek.dk
      secretName: production-platform-tls
