apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: production-redirect-to-https@kubernetescrd,production-security-headers@kubernetescrd,production-rate-limit@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - lmbek.dk
        - placeholder1.lmbek.dk
        - placeholder2.lmbek.dk
        - docs.lmbek.dk
        - web.lmbek.dk
      secretName: production-platform-tls
  rules:
    - host: lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-frontend
                port:
                  name: http
    - host: placeholder1.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: placeholder1-service
                port:
                  name: http
    - host: placeholder2.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: placeholder2-service
                port:
                  name: http
    - host: docs.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  name: http
    - host: web.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-frontend
                port:
                  name: http
