apiVersion: v1
kind: Service
metadata:
  name: placeholder1-service
  labels:
    app.kubernetes.io/name: placeholder1-service
spec:
  ports:
    - name: http
      port: 8082
      targetPort: http
  selector:
    app.kubernetes.io/name: placeholder1-service
---
apiVersion: v1
kind: Service
metadata:
  name: placeholder2-service
  labels:
    app.kubernetes.io/name: placeholder2-service
spec:
  ports:
    - name: http
      port: 8081
      targetPort: http
  selector:
    app.kubernetes.io/name: placeholder2-service
