apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-frontend
                port:
                  name: http
    - host: placeholder1.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: placeholder1-service
                port:
                  name: http
    - host: placeholder2.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: placeholder2-service
                port:
                  name: http
    - host: docs.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  name: http
    - host: web.lmbek.dk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-frontend
                port:
                  name: http
