apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - websites
  - applications
  - docs
  - middlewares.yml
  - ingress.yml
  - network-policies.yml
  - resource-limits.yml
